// <auto-generated />
using System;
using DigitalPark.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalPark.Persistence.Migrations
{
    [DbContext(typeof(DigitalParkDbContext))]
    [Migration("20230214101137_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigitalPark.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("DigitalPark.Domain.Entities.EventContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderNr")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "OrderNr")
                        .IsUnique();

                    b.ToTable("EventContents", (string)null);
                });

            modelBuilder.Entity("DigitalPark.Domain.Entities.EventContentTransation", b =>
                {
                    b.Property<int>("EventContentId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventContentId", "LanguageCode");

                    b.HasIndex("LanguageCode");

                    b.ToTable("EventContentTranslations", (string)null);
                });

            modelBuilder.Entity("DigitalPark.Domain.Entities.EventTranslation", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EventId", "LanguageCode");

                    b.HasIndex("LanguageCode");

                    b.ToTable("EventTranslations", (string)null);
                });

            modelBuilder.Entity("DigitalPark.Domain.Entities.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Code");

                    b.ToTable("Languages", (string)null);
                });

            modelBuilder.Entity("DigitalPark.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("DigitalPark.Domain.Entities.LocationTranslation", b =>
                {
                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LocationId", "LanguageCode");

                    b.HasIndex("LanguageCode");

                    b.ToTable("LocationTranslations", (string)null);
                });

            modelBuilder.Entity("DigitalPark.Domain.Entities.Event", b =>
                {
                    b.HasOne("DigitalPark.Domain.Entities.Location", "Location")
                        .WithMany("Events")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DigitalPark.Domain.Entities.EventContent", b =>
                {
                    b.HasOne("DigitalPark.Domain.Entities.Event", "Event")
                        .WithMany("Contents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DigitalPark.Domain.Entities.EventContentTransation", b =>
                {
                    b.HasOne("DigitalPark.Domain.Entities.EventContent", "EventContent")
                        .WithMany("Translations")
                        .HasForeignKey("EventContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalPark.Domain.Entities.Language", "Language")
                        .WithMany("EventContentTransations")
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EventContent");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DigitalPark.Domain.Entities.EventTranslation", b =>
                {
                    b.HasOne("DigitalPark.Domain.Entities.Event", "Event")
                        .WithMany("Translations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalPark.Domain.Entities.Language", "Language")
                        .WithMany("EventTranslations")
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DigitalPark.Domain.Entities.LocationTranslation", b =>
                {
                    b.HasOne("DigitalPark.Domain.Entities.Language", "Language")
                        .WithMany("LocationTranslations")
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalPark.Domain.Entities.Location", "Location")
                        .WithMany("Translations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DigitalPark.Domain.Entities.Event", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("DigitalPark.Domain.Entities.EventContent", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("DigitalPark.Domain.Entities.Language", b =>
                {
                    b.Navigation("EventContentTransations");

                    b.Navigation("EventTranslations");

                    b.Navigation("LocationTranslations");
                });

            modelBuilder.Entity("DigitalPark.Domain.Entities.Location", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
